# Generated by Django 4.1.2 on 2022-10-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
